### ISSUE TITLE
Action is a noop (and no errors) when trigger is `release: [published]`

### ISSUE THREAD

**Issue by sgnn7** [vsoch/pull-request-action#20]
Currently if the trigger is a `release: [published]`, the [`BRANCH` variable](https://github.com/vsoch/pull-request-action/blob/e54bcbb815225f58f7c672a1a2eb065771532fc6/pull-request.sh#L109-L112) results in value of `null` and as such makes the action act as a `noop`. This also creates no errors in the run.

<img width="1080" alt="Screen Shot 2020-03-17 at 10 32 53" src="https://user-images.githubusercontent.com/175811/76872637-b1e22080-683a-11ea-91c5-d3fbaf6ab3c3.png">

To reproduce you can take a look at [this](https://github.com/conjurinc/playroom/blob/df256bb8bda32ff88c87a6bfc78ba452d42d1c8c/.github/workflows/update-suite-release-pr.yml) sample action file

**Comment by vsoch** [comment]
What would be the intended outcome for release, publish? There is no branch to publish to (because it' a release) so what would be the expected branch to "publish" to, and how would you see best handling this edge case? Happy to fix this up after some discussion, going to be afk for a bit but back after that so please talk your time.

**Comment by sgnn7** [comment]
@vsoch 

So the workflow that we're trying to do is this (I bolded the part that is relevant here):
- Release is published in the UI
- Action triggers:
  - Runs some tests (fake tests for now)
  - If tests pass:
     - Commit a new release of a file in `./releases/suite_<version>.yml` by copying `./suite.yml` there
     - Push that to a new branch `suite_<version>` (master is protected so we can't push to master)
     - **Open a PR from `suite_<version>` branch to default branch (`master`) for this change**
     - Dev manually approves/merges the PR

**Comment by sgnn7** [comment]
For the edge-case handling, I don't know the codebase well but I'll take a look. I'm wondering if having a way just to specify a source branch (not a matcher) that bypasses the later checking logic can be enough.

**Comment by sgnn7** [comment]
@vsoch This seems reasonable to me but I don't have a good way to test it other than my current use case: https://github.com/vsoch/pull-request-action/pull/21. Let me know what you think.

**Comment by vsoch** [comment]
A few quick questions! First - is `/releases/suite_<version>.yml` created and pushed by a human or another action? If it's pushed by an action and in the workflows folder (and thus considered a workflow) actions aren't allowed to update this folder. 

Second - is this logic all in the same workflow file? The reason is because actions cannot trigger other actions.

If a fix like the one you opened for the PR #21 is sufficient to fix your issue, then I can just review that and we would be good. Let me know your answers to the above, and preference.

**Comment by sgnn7** [comment]
> `is /releases/suite_<version>.yml created and pushed by a human or another action?` by another action. 

This is done in the same action (you can check [here](https://github.com/conjurinc/playroom/blob/df256bb8bda32ff88c87a6bfc78ba452d42d1c8c/.github/workflows/update-suite-release-pr.yml)). The release folder is not the GH release but a folder in the repo itself.

> Second - is this logic all in the same workflow file? 

Yes

> If a fix like the one you opened for the PR #21 is sufficient to fix your issue, then I can just review that and we would be good.

Give me an hour or two to make sure the patch works for my use case but that will be enough to get us going. Thanks!

**Comment by vsoch** [comment]
here you are @sgnn7 ! I integrated your commit as well, and wrote a clear description for how you can use (and set) the variable in the readme. Do you want to give it a try and give me feedback? https://github.com/vsoch/pull-request-action/pull/22

**Comment by sgnn7** [comment]
Sure!
