### ISSUE TITLE
Failing without FAIL_ON_ERROR on PR 404

### ISSUE THREAD

**Issue by AnandChowdhary** [vsoch/pull-request-action#44]
Perhaps I'm wrong, but I'm assuming having an unset `FAIL_ON_ERROR` means that it shouldn't fail, right?

Unfortunately I haven't been able to reproduce this in the testing repo (maybe it happened because this is a private repo), but I got this error:

![Screen Shot 2020-09-25 at 19 50 05](https://user-images.githubusercontent.com/2841780/94278349-5373c880-ff68-11ea-9784-dc4e22882489.png)

```log
Data for checking if pull request exists: {'base': 'master', 'head': 'feature-single-build-process', 'body': '🚀 Opening a pull request for this branch'}
Error, but FAIL_ON_ERROR is not set, continuing: Unable to retrieve information about pull requests: 404: Not Found
▶ github pr response
  {'message': 'Not Found', 'documentation_url': 'https://docs.github.com/rest/reference/pulls#list-pull-requests'}
```

Seems like it got a 404 when fetching pre-existing PR details, which resulted in the workflow throwing an error. However, since `FAIL_ON_ERROR` is not set, I would expect it to continue and end up with a passed status check. In this case, no PR was created and the check failed.

Quick thoughts:
- Maybe it's getting a 404 because the authentication token is not proper? If you request a private repo that you don't have access to GitHub throws a 404, so this could be an instance of that
- Maybe we might have to wrap some of these into a try-catch block? Otherwise it might crash the process, resulting in a failed check even if `FAIL_ON_ERROR` is not set

**Comment by vsoch** [comment]
`FAIL_ON_ERROR` set in the environment means that you will fail on error. In the above, it fails but doesn't exit because you do not have it set. The issue is a 404 error, so the branch or repository are not found. Why would you request a private repository that you don't have access to? That obviously wouldn't be allowed!

**Comment by AnandChowdhary** [comment]
No, I'm requesting a private repository I do have access to. 😄

**Comment by vsoch** [comment]
Does the branch and repository exist? If GitHub is telling you 404, not found, there is something that is either not found (incorrectly specified) or you don't have permission to access it. I don't think this is an issue with the pull request action because the call is done correctly, and it's just telling you based on the parameters what you want doesn't exist.

**Comment by vsoch** [comment]
Are you sure your master branch is called master and not main?

**Comment by vsoch** [comment]
Ah I think I might know the issue! See the details here https://github.com/vsoch/pull-request-action/issues/45#issuecomment-699235843 what we can do is add an IS_PRIVATE variable that, if present, will add authentication headers to the request to get the repo (to see if the PR is open). I suspect that's why you are getting 404.

**Comment by vsoch** [comment]
@AnandChowdhary could you please test the update/python-client branch - I added a check for 404 and then to do the response again with headers! https://github.com/vsoch/pull-request-action/commit/cd4e27d2e27b63ba63b8fd66ae9408124045c0bd

**Comment by vsoch** [comment]
https://github.com/vsoch/pull-request-action/releases/tag/1.0.10

**Comment by AnandChowdhary** [comment]
This is great, thanks so much!
