### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by JooHyukKim** [vsoch/pull-request-action#99]
Our ci is failing on `docker build` task. Anyone else having the same problem?

![image](https://github.com/vsoch/pull-request-action/assets/61615301/59d17669-72c9-49db-8bd9-558764847fa0)

**Comment by JooHyukKim** [comment]
> Ah yeah I think I've seen this - with newer OS they get angry if you install to system python. Let me take a look.

Thanksss!, idk if it's the host in Gihtub  datacenter or the image registry

**Comment by vsoch** [comment]
@JooHyukKim here is the fix: https://github.com/vsoch/pull-request-action/pull/100

Since it builds from the Dockerfile, to test you should be able to target that branch, e.g., the action name `@update-container-base`. Let me know if it works! The build works locally for me, so we'd want to sanity check the virtual environment entrypoint is still good.

**Comment by vsoch** [comment]
> Thanksss!, idk if it's the host in Gihtub datacenter or the image registry

It's likely the image in the docker registry "alpine" has a new latest with this change.

**Comment by JooHyukKim** [comment]
sick! Will let you know aspa

**Comment by vsoch** [comment]
okay let's merge! All my actions that use this are in the process of throwing up on me too, lol. Thanks for the quick report!
